# Generated by Django 6.0.4 on 2026-04-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_room_acessibilidade_alter_room_aprovador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_column="nm_layout",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Layout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout de Sala",
                "verbose_name_plural": "Layouts de Sala",
                "db_table": "tb_layout_sala",
                "ordering": ("nome",),
            },
        ),
        migrations.AddField(
            model_name="room",
            name="descricao_detalhada",
            field=models.TextField(
                blank=True,
                db_column="descricao_detalhada",
                null=True,
                verbose_name="Descrição Detalhada",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="link_google_maps",
            field=models.URLField(
                blank=True,
                db_column="link_google_maps",
                max_length=500,
                null=True,
                verbose_name="Link do Google Maps",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="metragem_m2",
            field=models.DecimalField(
                blank=True,
                db_column="metragem_m2",
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Metragem (m²)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="planta_baixa",
            field=models.FileField(
                blank=True,
                db_column="planta_baixa",
                null=True,
                upload_to="room_plans/",
                verbose_name="Planta Baixa (PDF)",
            ),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        db_column="arquivo",
                        upload_to="room_images/",
                        verbose_name="Arquivo da Foto",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True,
                        db_column="legenda",
                        max_length=150,
                        null=True,
                        verbose_name="Legenda",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_column="ordem", default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "is_principal",
                    models.BooleanField(
                        db_column="is_principal",
                        default=False,
                        verbose_name="Foto Principal",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_column="sala_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="core.room",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto da Sala",
                "verbose_name_plural": "Fotos da Sala",
                "db_table": "tb_foto_sala",
                "ordering": ("ordem", "id"),
            },
        ),
        migrations.AddField(
            model_name="room",
            name="layouts_permitidos",
            field=models.ManyToManyField(
                blank=True,
                db_table="tb_sala_layout",
                related_name="salas",
                to="core.roomlayout",
                verbose_name="Layouts Permitidos",
            ),
        ),
    ]
